#This setting determines what will cause the Display Notches to automatically rotate. The following values are available:
#SIGNAL: A redstone signal will trigger it.
#TORCH_ITEM: Right-clicking with a Redstone Torch will trigger it.
#Allowed Values: SIGNAL, TORCH_ITEM
spinningSource = "SIGNAL"
