#Only enable if you want to test the experimental backup system.
enabled = false
#Defines the backup type.
#- FULL_BACKUPS - every backup is a full backup.
#- INCREMENTAL  - backup only files changed since the last backup
#- DIFFERENTIAL - backup only files changed since the last full backup
#Allowed Values: FULL_BACKUPS, INCREMENTAL, DIFFERENTIAL
backupType = "INCREMENTAL"
#The max amount of backup chains to keep.
# Default: 10
# Range: 1 ~ 32767
backupChainsToKeep = 10
